apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: mongodb
data:
  database_url: mongodb-service # ketu vendosim service te mongo db, pra na duhet ip addresa e atij service qe te komunikojme me mongodb
