apiVersion: v1
kind: Service
metadata:
  name: minesweeper-game-service
  namespace: devops-training
spec:
  selector:
    app: minesweeper-game
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 80
