apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  namespace: suhejl
  labels:
    app: sample-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
        - name: python-app
          imagePullPolicy: Always
          image: abhishekf5/python-sample-app-demo:v1
          volumeMounts:
            - name: db-connection
              mountPath: /opt
          ports:
            - containerPort: 8000
      volumes:
        - name: db-connection
          configMap:
            name: test-cm
