apiVersion: v1
kind: Service
metadata:
  name: mysql-app
  namespace: devops-training
spec:
  type: NodePort
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30600
