apiVersion: v1
kind: Service
metadata:
  name: html-app
  namespace: devops-training
spec:
  type: NodePort
  selector:
    app: html-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30300
