apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-1
  namespace: resource-quota
  labels:
    app: web-app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-1
  template:
    metadata:
      labels:
        app: web-app-1
    spec:
      containers:
        - name: web-app-1
          imagePullPolicy: Always
          image: suhejlvejseli/web-app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              # cpu: "0.5"
            limits:
              memory: "512Mi"
              # cpu: "1"
