---
apiVersion: v1
kind: Namespace
metadata:
  name: resource-quota

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: labs-resource-quotas-assignment
  namespace: resource-quota
spec:
  hard:
    # pods: "3"
    # requests.cpu: "1"
    requests.memory: 1Gi
    # limits.cpu: "2"
    limits.memory: 2Gi
