apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: labs
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          imagePullPolicy: Always
          image: suhejlvejseli/web-app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-2
  namespace: labs
  labels:
    app: web-app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-2
  template:
    metadata:
      labels:
        app: web-app-2
    spec:
      containers:
        - name: web-app-2
          imagePullPolicy: Always
          image: suhejlvejseli/web-app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
